In [ ]:
import numpy as np

# Original array with 20 elements
arr = np.arange(1, 21)  # [1, 2, ..., 20]

# Reshape examples
print("1x20:\n", arr.reshape(1, 20))
print("\n4x5:\n", arr.reshape(4, 5))
print("\n5x4:\n", arr.reshape(5, 4))
print("\n10x2:\n", arr.reshape(10, 2))
print("\n2x10:\n", arr.reshape(2, 10))


1x20:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]

4x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

5x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

10x2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

2x10:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
import numpy as np

# Creating an array from 0 to 9
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# 5 evenly spaced values between 0 and 10
a = np.linspace(0, 10, 5)
print(a)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np

a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

a = np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

# Creating an array with 30 elements
arr = np.arange(30)
print("Original Array:\n", arr)
print("Reshaped to 5x6:\n", arr.reshape(5, 6))
print("\nReshaped to 3x10:\n", arr.reshape(3, 10))
print("\nReshaped to 2x15:\n", arr.reshape(2, 15))
print("\nReshaped to 6x5:\n", arr.reshape(6, 5))
print("Auto Reshape (5 rows):\n", arr.reshape(5, -1))  # Automatically calculates 6 columns
print("\nAuto Reshape (3 columns):\n", arr.reshape(-1, 3))  # Automatically calculates rows


Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Reshaped to 5x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Reshaped to 3x10:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

Reshaped to 2x15:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

Reshaped to 6x5:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Auto Reshape (5 rows):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Auto Reshape (3 columns):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [ ]:
# numpy operation for addition subtraction division and multiplication

import numpy as np

# Sample arrays for operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Addition
addition_result = arr1 + arr2
print("Addition:", addition_result)

# Subtraction
subtraction_result = arr2 - arr1
print("Subtraction:", subtraction_result)

# Multiplication
multiplication_result = arr1 * arr2
print("Multiplication:", multiplication_result)

# Division
division_result = arr2 / arr1
print("Division:", division_result)


Addition: [ 7  9 11 13 15]
Subtraction: [5 5 5 5 5]
Multiplication: [ 6 14 24 36 50]
Division: [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
# arithematic operation using numpy add inverse and power in the function

import numpy as np

def numpy_operations(arr1, arr2):

  addition_result = np.add(arr1, arr2)
  inverse_result = np.linalg.inv(arr1) if arr1.ndim > 0 else 1/arr1 # Handle 0-D arrays for inverse

  power_result = np.power(arr1, arr2)

  return addition_result, inverse_result, power_result


# Example usage:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

addition, inverse, power = numpy_operations(arr1, arr2)

print("Addition:\n", addition)
print("\nInverse:\n", inverse)
print("\nPower:\n", power)


Addition:
 [[ 6  8]
 [10 12]]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Power:
 [[    1    64]
 [ 2187 65536]]


In [ ]:
# matrix multioplication

import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result_matrix = np.matmul(matrix1, matrix2)

# Print the result
print("Matrix Multiplication Result:\n", result_matrix)


Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [ ]:
# SOLVE THE EQUATIONS USING MATRIX MULTIPLICATION

import numpy as np
# Define the coefficient matrix A and the constant matrix B
A = np.array([[2, 3], [1, -1]])
B = np.array([8, 1])

# Solve for X using matrix multiplication
X = np.linalg.solve(A, B)

# Print the solution
print("Solution (X):\n", X)



Solution (X):
 [2.2 1.2]


In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 2, 3], [2, 3, 1], [1, 1, 2]])

# Constant matrix
B = np.array([10, 15, 20])

# Solving the system of equations
solution = np.linalg.solve(A, B)

# Display the solution
print("Solution for X, Y, Z:", solution)


Solution for X, Y, Z: [ 26.25 -13.75   3.75]


In [ ]:
# TRANSPOSE OF A MATRIX

import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Transpose the matrix using numpy.transpose()
transposed_matrix = np.transpose(matrix)

# Print the original and transposed matrices
print("Original Matrix:\n", matrix)
print("\nTransposed Matrix:\n", transposed_matrix)

# Alternatively, you can also use the .T attribute of a numpy array
transposed_matrix_2 = matrix.T

print("\nTransposed Matrix (using .T):\n", transposed_matrix_2)


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transposed Matrix (using .T):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# functions to generate random functions

import random
import numpy as np

def generate_random_function():
  """Generates a random function using numpy operations."""

  def random_function(x):
    operation_choices = [np.add, np.subtract, np.multiply, np.divide, np.power]
    operation = random.choice(operation_choices)

    if operation in [np.add, np.subtract, np.multiply, np.divide]:
      y = random.randint(1, 10)
      return operation(x, y)
    elif operation == np.power:
      y = random.randint(1, 3)
      return operation(x, y)
    else:
      return x  # Default case

  return random_function

# Example usage:
my_random_function = generate_random_function()

for x in range(5):
  print(f"x: {x}, result: {my_random_function(x)}")


x: 0, result: 0
x: 1, result: 5
x: 2, result: 0.2857142857142857
x: 3, result: 12
x: 4, result: 64


In [ ]:
#  GENERATE 5X5 MATRIX AND 2ND ROW, 2ND COLUMNS, 4TH ROW AND 4TH COLUMNS PRINT ELEMENTS

import numpy as np

matrix = np.random.randint(1, 100, size=(5, 5))

print("5x5 Matrix:\n", matrix)

print("\nElement at 2nd row and 2nd column:", matrix[1, 1])

print("\nElement at 4th row and 4th column:", matrix[3, 3])


5x5 Matrix:
 [[38 42 51 89 66]
 [46 59 74 67 82]
 [15 19 41 79 33]
 [ 5 99 93 78 13]
 [65 25 13 52 51]]

Element at 2nd row and 2nd column: 59

Element at 4th row and 4th column: 78


In [ ]:
#creating series from list and numpy array

import pandas as pd

# Creating a Series from a list
my_list = [10, 20, 30, 40, 50]
series_from_list = pd.Series(my_list)
print("Series from list:\n", series_from_list)


# Creating a Series from a NumPy array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
series_from_array = pd.Series(my_array)
print("\nSeries from NumPy array:\n", series_from_array)


Series from list:
 0    10
1    20
2    30
3    40
4    50
dtype: int64

Series from NumPy array:
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
#performing mathematical operations on panda series

import pandas as pd

# Sample Series
data = {'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10]}
df = pd.DataFrame(data)
series_a = df['A']

# Mathematical operations
print("Original Series A:\n", series_a)

# Addition
series_add = series_a + 2
print("\nSeries A + 2:\n", series_add)

# Subtraction
series_sub = series_a - 2
print("\nSeries A - 2:\n", series_sub)


# Multiplication
series_mul = series_a * 2
print("\nSeries A * 2:\n", series_mul)

# Division
series_div = series_a / 2
print("\nSeries A / 2:\n", series_div)


Original Series A:
 0    1
1    2
2    3
3    4
4    5
Name: A, dtype: int64

Series A + 2:
 0    3
1    4
2    5
3    6
4    7
Name: A, dtype: int64

Series A - 2:
 0   -1
1    0
2    1
3    2
4    3
Name: A, dtype: int64

Series A * 2:
 0     2
1     4
2     6
3     8
4    10
Name: A, dtype: int64

Series A / 2:
 0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
Name: A, dtype: float64


In [ ]:
# student dataframe creation

import pandas as pd

# Sample student data (replace with your actual data)
student_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [18, 19, 17, 20, 18],
    'Grade': ['A', 'B', 'C', 'A', 'B'],
    'Major': ['Computer Science', 'Physics', 'Mathematics', 'Engineering', 'Biology']
}

# Create a Pandas DataFrame
df = pd.DataFrame(student_data)

# Display the DataFrame
df


Name  Age Grade             Major
0    Alice   18     A  Computer Science
1      Bob   19     B           Physics
2  Charlie   17     C       Mathematics
3    David   20     A       Engineering
4      Eve   18     B           Biology

In [ ]:
# data frame creation with student, grade, num and roll no.

import pandas as pd

# Sample data for the DataFrame
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Grade': ['A', 'B', 'C', 'A'],
    'Num': [1, 2, 3, 4],
    'Roll No': [101, 102, 103, 104]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df


Student Grade  Num  Roll No
0    Alice     A    1      101
1      Bob     B    2      102
2  Charlie     C    3      103
3    David     A    4      104

In [ ]:
# creating a pandas dataframe using a dictionary

import pandas as pd
# Sample data for the DataFrame
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David'],
    'Grade': ['A', 'B', 'C', 'A'],
    'Num': [1, 2, 3, 4],
    'Roll No': [101, 102, 103, 104]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df


Student Grade  Num  Roll No
0    Alice     A    1      101
1      Bob     B    2      102
2  Charlie     C    3      103
3    David     A    4      104

In [ ]:
#create a dataframe for random integers value

import pandas as pd
import numpy as np

# Create a DataFrame with 10 rows and 3 columns of random integers between 1 and 100
data = np.random.randint(1, 101, size=(10, 3))
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

df


Column1  Column2  Column3
0       28       68       20
1       56       13       92
2       91        8       91
3       19       34       73
4       83       83       77
5       52        6       27
6       38       89       24
7       73       48       45
8      100       21       21
9       80       25       60

In [ ]:
# open csv file

import pandas as pd

try:
    df = pd.read_csv('StockData.csv')
    print(df)
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please upload the file or provide the correct path.")


     stock        date    price
0     AAPL  08-02-2013  67.8542
1     AAPL  11-02-2013  68.5614
2     AAPL  12-02-2013  66.8428
3     AAPL  13-02-2013  66.7156
4     AAPL  14-02-2013  66.6556
...    ...         ...      ...
5031   ZTS  01-02-2018  77.8200
5032   ZTS  02-02-2018  76.7800
5033   ZTS  05-02-2018  73.8300
5034   ZTS  06-02-2018  73.2700
5035   ZTS  07-02-2018  73.8600

[5036 rows x 3 columns]


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   stock   5036 non-null   object 
 1   date    5036 non-null   object 
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB


In [ ]:
df.isnull().sum()

stock    0
date     0
price    0
dtype: int64

In [ ]:
df.dtypes

stock     object
date      object
price    float64
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

price
count  5036.000000
mean     73.057030
std      29.011126
min      28.400000
25%      54.067500
50%      69.085000
75%      79.250000
max     179.260000

In [ ]:
df['stock'].nunique()

4

In [ ]:
df['stock'].value_counts()

stock
AAPL    1259
SNI     1259
TJX     1259
ZTS     1259
Name: count, dtype: int64

In [ ]:
df=pd.read_excel('new.xlsx')

In [ ]:
df.head()

stock                 date    price
0  AAPL  2013-08-02 00:00:00  67.8542
1  AAPL  2013-11-02 00:00:00      NaN
2  AAPL  2013-12-02 00:00:00      NaN
3  AAPL           13-02-2013      NaN
4  AAPL           14-02-2013  66.6556

In [ ]:
round(df['price'].mean())

73

In [ ]:
round(df['price'].mode())

0    75.0
Name: price, dtype: float64

In [ ]:
round(df['price'].median())

69

In [ ]:
df.sort_values(by='price')

stock                 date   price
4072   ZTS  2014-11-04 00:00:00   28.40
4073   ZTS           14-04-2014   28.48
4075   ZTS           16-04-2014   28.53
4074   ZTS           15-04-2014   28.55
4076   ZTS           17-04-2014   28.60
...    ...                  ...     ...
1243  AAPL           17-01-2018  179.10
1244  AAPL           18-01-2018  179.26
1     AAPL  2013-11-02 00:00:00     NaN
2     AAPL  2013-12-02 00:00:00     NaN
3     AAPL           13-02-2013     NaN

[5036 rows x 3 columns]

In [ ]:
round(df['price'].sum())

367713

In [ ]:
import pandas as pd

try:
    df1 = pd.read_csv('Predictive_Maintenance_Case_Study.csv')
    print(df)
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please upload the file or provide the correct path.")


        UDI Type  Air temperature  Process temperature  Rotational speed  \
0         1    M            298.1           323.740741              1551   
1         2    L            298.2           324.111111              1408   
2         3    L            298.1           323.370370              1498   
3         4    L            298.2           323.740741              1433   
4         5    L            298.2           324.111111              1408   
...     ...  ...              ...                  ...               ...   
9995   9996    M            298.8           323.000000              1604   
9996   9997    H            298.9           323.000000              1632   
9997   9998    M            299.0           323.740741              1645   
9998   9999    H            299.0           324.111111              1408   
9999  10000    M            299.0           324.111111              1500   

      Torque  Tool wear  Failure  
0       42.8          0        0  
1       46.3     